version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: jaydevstack-store-miner-radar_server_1
      APP_PORT: 3021
    
  server:
    image: jaydevstack/miner-radar:v0.1.0@sha256:856de064513ac977d12d5763a1d0cf9783f799a301ed33249519bc91de8754b5
    init: true
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
